# Generated by Django 4.1.5 on 2023-01-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stdb_code',
            new_name='stbd_code',
        ),
    ]
